name: Build Tagged Companion App
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    env:
      working-directory: ./companion_app

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
      working-directory: ${{ env.working-directory }}
    - run: flutter build apk
      working-directory: ${{ env.working-directory }}

    - run: cp -v companion_app/build/app/outputs/apk/release/app-release.apk ./linux-android-backup-companion.apk
    - run: sudo apt update && sudo apt install p7zip-full
    - run: 7z a -bb3 -t7z -mx9 -x!companion_app\* Linux_Android_Backup_${{ github.ref_name }}_Bundle.7z .

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: "Linux Android Backup Stable - ${{ github.ref_name }}"
        files: |
          companion_app/build/app/outputs/apk/release/app-release.apk
          Linux_Android_Backup_${{ github.ref_name }}_Bundle.7z