name: Build Unstable Companion App
on:
  push:
    paths:
      - 'companion_app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./companion_app
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
      working-directory: ${{ env.working-directory }}
    - run: flutter build apk
      working-directory: ${{ env.working-directory }}

    - run: cp -v companion_app/build/app/outputs/apk/release/app-release.apk ./linux-android-backup-companion.apk
    - run: sudo apt update && sudo apt install p7zip-full
    - run: 7z a -bb3 -t7z -mx9 -x!companion_app\* Linux_Android_Backup_Unstable_Bundle.7z .

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest" # we need to keep this tag to keep legacy scripts working
        prerelease: true
        title: "Companion App - Unstable Version"
        files: |
          companion_app/build/app/outputs/apk/release/app-release.apk
          Linux_Android_Backup_Unstable_Bundle.7z
