name: Build Unstable
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./companion_app
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
      working-directory: ${{ env.working-directory }}
    - run: flutter build apk
      working-directory: ${{ env.working-directory }}

    - run: cp -v companion_app/build/app/outputs/apk/release/app-release.apk ./open-android-backup-companion.apk
    - run: sudo apt update && sudo apt install p7zip-full
    - run: 7z a -bb3 -tzip -mx9 -x!.*\* -x!website\* -x!companion_app\* Open_Android_Backup_Unstable_Bundle.zip .

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest" # we need to keep this tag for legacy scripts to work (and as a fallback)
        prerelease: true
        title: "Open Android Backup - Unstable Version"
        files: |
          companion_app/build/app/outputs/apk/release/app-release.apk
          Open_Android_Backup_Unstable_Bundle.zip
